# ************************************************************************* #
#                                                                           #
#                                                      :::      ::::::::    #
#  arguments_checker.py                              :+:      :+:    :+:    #
#                                                  +:+ +:+         +:+      #
#  By: roandrie <roandrie@student.42lehavre.fr   +#+  +:+       +#+         #
#                                              +#+#+#+#+#+   +#+            #
#  Created: 2026/03/27 14:02:23 by roandrie        #+#    #+#               #
#  Updated: 2026/04/22 21:07:38 by roandrie        ###   ########.fr        #
#                                                                           #
# ************************************************************************* #
"""
Command-line argument parsing module for the Call Me Maybe tool.

This module provides the configuration for the CLI, including path validation
for JSON input/output files and various execution flags.
It ensures that all user inputs are properly structured before the main
logic begins.
"""

from typing import NoReturn
from argparse import Namespace

import argparse
import sys

from src.parser.path_checker import validate_json_input, validate_json_output
from src.utils import print_error


class RichArgumentParser(argparse.ArgumentParser):
    """
    Custom ArgumentParser that leverages Rich for enhanced error reporting.

    This class overrides the default error handling to ensure all CLI errors
    are displayed using the project's styled output utilities.
    """

    def error(self, message: str) -> NoReturn:
        """
        Handle parsing errors by displaying a styled message and exiting.

        Args:
            message (str): The error message generated by argparse.
        """
        print_error(message)
        self.print_usage(sys.stderr)
        sys.exit(2)


def argument_parser() -> argparse.Namespace:
    """
    Initialize and execute the command-line argument parsing.

    This function defines the available CLI options for function definitions,
    input test files, output result files, and execution flags.

    Returns:
        argparse.Namespace: An object containing the validated command-line
                            arguments.
    """
    # Create the parser object
    parser: RichArgumentParser = RichArgumentParser(
        prog="Call Me Maybe",
        description=("Function calling tool that translates natural "
                     "language prompts into structured function calls"),
        usage=("python -m src [--functions_definition "
               "<function_definition_file>] [--input <input_file>] "
               "[--output <output_file>]"),
        epilog=" ",
        formatter_class=argparse.RawTextHelpFormatter
    )

    # Add function definition argument (store functions definition)
    parser.add_argument(
        "-f", "--functions_definition",
        help=("path where function definition in json is stored.\n"
              "default: data/input/functions_definition.json)\n\n"),
        default="data/input/functions_definition.json",
        metavar="file.json",
        dest="func_def",
        type=validate_json_input
    )

    # Add function calling argument (store function calling)
    parser.add_argument(
        "-i", "--input",
        help=("path where input file in json is stored.\n"
              "(default: data/input/function_calling_tests.json)\n\n"),
        default="data/input/function_calling_tests.json",
        metavar="file.json",
        dest="func_call",
        type=validate_json_input
    )

    # Add output file argument
    parser.add_argument(
        "-o", "--output",
        help=("path to the output file in json.\n"
              "(default: data/output/function_calling_results.json)\n\n"),
        default="data/output/function_calling_results.json",
        metavar="file.json",
        type=validate_json_output
    )

    # Add model name
    parser.add_argument(
        "-m", "--model",
        help=("name of the model you want to use.\n"
              "(default: 'Qwen/Qwen3-0.6B')"),
        default="Qwen/Qwen3-0.6B",
        type=str
    )

    # Add visualizer argument
    parser.add_argument(
        "-v", "--visualizer",
        help="launch with the visualizer\n\n",
        required=False,
        action="store_true"
    )

    # Add debug argument
    parser.add_argument(
        "-d", "--debug",
        help="launch with the debug mode",
        required=False,
        action="store_true"
    )

    # Store all arguments
    args: Namespace = parser.parse_args()

    return args
